### ISSUE TITLE
pagination issue 

### ISSUE THREAD

**Issue by dineshprasanna** [fedefrappi/AePubReader#7]
i am trying to load an epub file in chapter wise into the webview. I want to know the width of the screen.

For Example:

if the content have one and half page text means it returns the width to be as 768
but
if the content have two full page text means it returns the width to be as 1536

my code is:

int totalWidth = [[webView stringByEvaluatingJavaScriptFromString:@"document.documentElement.scrollWidth"] intValue];

please help me.....

**Comment by WebberLai** [comment]
I found some answer , but I not try it 

// get the width of your content
[webview stringByEvaluatingJavaScriptFromString:@"document.getElementById('id_of_content_container').offsetWidth;"];

Did you set this webView.scalesPageToFit = YES; ???

**Comment by dineshprasanna** [comment]
Thanks Sir,I tried but it returns zero for scroll width, is there any other way to rectify it

**Comment by dineshprasanna** [comment]
now  its working for me, thanks sir

**Comment by fngr** [comment]
The problem is that you call updatePagination in shouldRotate... this is incorrect, it has been called 2 times.

CHANGE THIS:
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
      [self updatePagination];
  return YES;
  }

FOR THIS:
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
  
  return YES;
  }
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation{
  [self updatePagination];
  }
